### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by ryanknutson** [mtolly/X360#1]
Thanks for uploading this! I actually know Skunkiebutt, and he has said that this code is pretty outdated. :P

**Comment by mtolly** [comment]
No problem! Outdated it may be, but I and others in the Rock Band customs community still rely heavily on it to generate STFS packages, and I've yet to run into problems :) Has he posted a newer version publicly?

**Comment by ryanknutson** [comment]
Sorry for the late reply, but no. He hasn't maintained it.
